# Generated by Django 4.2.5 on 2023-12-05 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SECFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessionNo', models.CharField(default='Not found', max_length=100, unique=True)),
                ('cik', models.CharField(max_length=15)),
                ('ticker', models.CharField(max_length=10)),
                ('companyName', models.CharField(max_length=200)),
                ('companyNameLong', models.CharField(max_length=500)),
                ('formType', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('linkToFilingDetails', models.URLField()),
                ('linkToTxt', models.URLField()),
                ('linkToHtml', models.URLField()),
                ('linkToXbrl', models.URLField(blank=True, null=True)),
                ('filedAt', models.DateTimeField()),
                ('periodOfReport', models.DateField(blank=True, null=True)),
                ('effectivenessDate', models.DateField(blank=True, null=True)),
                ('registrationForm', models.CharField(blank=True, max_length=20, null=True)),
                ('referenceAccessionNo', models.CharField(blank=True, max_length=100, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_service.stock')),
            ],
        ),
    ]
