# Generated by Django 4.2.5 on 2023-12-05 19:43

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import nlp_service.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sec_filings_service', '0001_initial'),
        ('stock_news_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedSECData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('processed_data', models.JSONField()),
                ('ticker', models.CharField(max_length=10)),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sec_filings_service.secfiling')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedGDELTData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('processed_data', models.JSONField()),
                ('summary_embedding', models.JSONField(default=nlp_service.models.default_float_list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_news_service.gdeltevent')),
            ],
        ),
    ]
